services:
  # postgres DB service
  database:
    image: postgres:16.1-alpine3.18
    container_name: order-engine-database
    restart: always
    ports:
      - ${DB_FORWARD_PORT:-5432}:5432
    environment:
      - POSTGRES_USER=${DB_USER:-order_user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-order_pass}
      - POSTGRES_DB=${DB_NAME:-order_engine}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - order_engine_network

  # pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: order-engine-pgadmin
    restart: always
    ports:
      - ${PGADMIN_FORWARD_PORT:-8888}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - order_engine_network

  # RabbitMQ service
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: order-engine-rabbitmq
    restart: always
    ports:
      - '${RABBITMQ_FORWARD_PORT:-5672}:5672'
      - '${RABBITMQ_MANAGEMENT_FORWARD_PORT:-15672}:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-rabbit_user}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-rabbit_pass}
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    networks:
      - order_engine_network

  # Backend service
  backend:
    container_name: order-engine-backend
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - ${APP_FORWARD_PORT:-8080}:${APP_PORT:-8080}
    volumes:
      - .:/app
    networks:
      - order_engine_network
    restart: on-failure
    tty: true
    stdin_open: true
    expose:
      - ${APP_PORT:-8080}

networks:
  order_engine_network:
    name: order-engine-shared-network
    external: true

volumes:
  pgdata: {}
  pgadmin_data: {}
  rabbitmqdata: {}
