services:
  backend:
    container_name: order-engine-backend-dev
    build:
      context: .
      target: build
    command: ['dumb-init', 'npm', 'run', 'start:dev']
    ports:
      - ${APP_FORWARD_PORT:-8080}:${APP_PORT:-8080}
      - '9229:9229'
    volumes:
      - .:/app
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - RABBITMQ_URL=amqp://${RABBITMQ_USERNAME:-rabbit_user}:${RABBITMQ_PASSWORD:-rabbit_pass}@rabbitmq:5672
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure
    tty: true
    stdin_open: true
    networks:
      - order_engine_network

networks:
  order_engine_network:
    name: order-engine-shared-network
    external: true
